title: Mecánica Analítica Computacional
# title: Computational Analytical Mechanics
author:
  name: Victor Bettachini
  # email: "ask@for.it"
logopath: https://raw.githubusercontent.com/unlam/MecanicaAnaliticaComputacional/refs/heads/main/figurasLaTeX/ambos.svg
docs/assets/img/bothLogo.svg
logowidth: 100
logoalt: DIIT UNLaM
logolink: https://ingenieria.unlam.edu.ar/
# author: Víctor Bettachini
# email: vbettachini@unlam.edu.ar
description: >-
  DIIT UNLAM
baseurl: /MecanicaAnaliticaComputacional
# baseurl: /ComputationalAnalyticalMechanics
url: https://unlam.github.io/
github_username: unlam

# Build settings
theme: minima


# plugins:
  # - jekyll-feed

# header_pages:
  # - about.md
  # - portfolio.md
