title: Computational Analytical Mechanics
author:
  name: Victor Bettachini
  email: "ask@for.it"
logopath: assets/img/bothLogo.png
logowidth: 100
logoalt: Logo UNLAM
logolink: https://fra.utn.edu.ar/
# author: Edgardo Palazzo
# email: epalazzo@fra.utn.edu.ar
description: >-
  DIIT UNLAM
# baseurl: /MecanicaAnaliticaComputacional
baseurl: /ComputationalAnalyticalMechanics
# url: https://bettachini.github.io/
url: https://frautn.github.io/
# github_username: bettachini
github_username: frautn

# Build settings
theme: minima


# plugins:
  # - jekyll-feed

# header_pages:
  # - about.md
  # - portfolio.md
